#pragma once

enum Keys {
  KEY_QUIT = 0,
  KEY_FORWARD = 1,
  KEY_BACKWARD = 2,
  KEY_LEFT = 3,
  KEY_RIGHT = 4,
  KEY_SHADER1 = 5,
  KEY_SHADER2 = 6,
  KEY_SHADER3 = 7,
  KEY_SHADER4 = 8,
  KEY_SHADER5 = 9,
  KEY_SWITCH = 10,
  KEY_ACTION = 11,
  KEY_MOVE_TOGGLE = 12,
  KEY_LIGHT1_TOGGLE = 13,
  KEY_LIGHT2_TOGGLE = 14,
  KEY_LIGHT3_TOGGLE = 15,
};
